In [ ]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix

%load_ext google.colab.data_table

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table


Conjunto de dados: Votos no congresso https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records

# Descrição das colunas (variáveis/atributos/features) do conjunto de dados

Attribute Information

    Class: democrat, republican
    Handicapped-infants: yes, no
    Water-project-cost-sharing: yes, no
    Adoption-of-the-budget-resolution: yes, no
    Physician-fee-freeze: yes, no
    El-salvador-aid: yes, no
    Religious-groups-in-schools: yes, no
    Anti-satellite-test-ban: yes, no
    Aid-to-nicaraguan-contras: yes, no
    Mx-missile: yes, no
    Immigration: yes, no
    Synfuels-corporation-cutback: yes, no
    Education-spending: yes, no
    Superfund-right-to-sue: yes, no
    Crime: yes, no
    Duty-free-exports: yes, no
    Export-administration-act-south-africa: yes, no
    

In [ ]:
dados = pd.read_csv("https://raw.githubusercontent.com/digiampietri/basesDeDados/main/voting-records.csv", names=['Class','Handicapped-infants','Water-project', 'Adoption', 'Physician', 'El-salvador', 'Religious', 'Anti-satellite', 'Nicaraguan','Mx-missile', 'Immigration', 'Synfuels', 'Education-spending','Superfund', 'Crime', 'Duty-fre-exports', 'Export-administration'])

In [ ]:
dados.head()

Class Handicapped-infants Water-project Adoption Physician  \
0  republican                   n             y        n         y   
1  republican                   n             y        n         y   
2    democrat                   ?             y        y         ?   
3    democrat                   n             y        y         n   
4    democrat                   y             y        y         n   

  El-salvador Religious Anti-satellite Nicaraguan Mx-missile Immigration  \
0           y         y              n          n          n           y   
1           y         y              n          n          n           n   
2           y         y              n          n          n           n   
3           ?         y              n          n          n           n   
4           y         y              n          n          n           n   

  Synfuels Education-spending Superfund Crime Duty-fre-exports  \
0        ?                  y         y     y                n   
1        n                  y         y     y                n   
2        y                  n         y     y                n   
3        y                  n         y     n                n   
4        y                  ?         y     y                y   

  Export-administration  
0                     y  
1                     ?  
2                     n  
3                     y  
4                     y

In [ ]:
dados.groupby('Class').count()

Handicapped-infants  Water-project  Adoption  Physician  \
Class                                                                 
democrat                    267            267       267        267   
republican                  168            168       168        168   

            El-salvador  Religious  Anti-satellite  Nicaraguan  Mx-missile  \
Class                                                                        
democrat            267        267             267         267         267   
republican          168        168             168         168         168   

            Immigration  Synfuels  Education-spending  Superfund  Crime  \
Class                                                                     
democrat            267       267                 267        267    267   
republican          168       168                 168        168    168   

            Duty-fre-exports  Export-administration  
Class                                                
democrat                 267                    267  
republican               168                    168

In [ ]:
dados.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Class                  435 non-null    object
 1   Handicapped-infants    435 non-null    object
 2   Water-project          435 non-null    object
 3   Adoption               435 non-null    object
 4   Physician              435 non-null    object
 5   El-salvador            435 non-null    object
 6   Religious              435 non-null    object
 7   Anti-satellite         435 non-null    object
 8   Nicaraguan             435 non-null    object
 9   Mx-missile             435 non-null    object
 10  Immigration            435 non-null    object
 11  Synfuels               435 non-null    object
 12  Education-spending     435 non-null    object
 13  Superfund              435 non-null    object
 14  Crime                  435 non-null    object
 15  Duty-fre-exports       

## Convertendo as características para características numéricas

In [ ]:
#Class [democrat, republican]
dados['Class'] = np.where(dados['Class'] == "democrat", 1, dados['Class'])
dados['Class'] = np.where(dados['Class'] == "republican", 2, dados['Class'])

#Handicapped-infants: [n = no, y = yes]
dados['Handicapped-infants'] = np.where(dados['Handicapped-infants'] == "n", 0, dados['Handicapped-infants'])
dados['Handicapped-infants'] = np.where(dados['Handicapped-infants'] == "?", 0.5, dados['Handicapped-infants'])
dados['Handicapped-infants'] = np.where(dados['Handicapped-infants'] == "y", 1, dados['Handicapped-infants'])

#Water-project: [n = no, y = yes]
dados['Water-project'] = np.where(dados['Water-project'] == "n", 0, dados['Water-project'])
dados['Water-project'] = np.where(dados['Water-project'] == "?", 0.5, dados['Water-project'])
dados['Water-project'] = np.where(dados['Water-project'] == "y", 1, dados['Water-project'])

#Adoption: [n = no, y = yes]
dados['Adoption'] = np.where(dados['Adoption'] == "n", 0, dados['Adoption'])
dados['Adoption'] = np.where(dados['Adoption'] == "?", 0.5, dados['Adoption'])
dados['Adoption'] = np.where(dados['Adoption'] == "y", 1, dados['Adoption'])

#Physician: [n = no, y = yes]
dados['Physician'] = np.where(dados['Physician'] == "n", 0, dados['Physician'])
dados['Physician'] = np.where(dados['Physician'] == "?", 0.5, dados['Physician'])
dados['Physician'] = np.where(dados['Physician'] == "y", 1, dados['Physician'])

#El-salvador: [n = no, y = yes]
dados['El-salvador'] = np.where(dados['El-salvador'] == "n", 0, dados['El-salvador'])
dados['El-salvador'] = np.where(dados['El-salvador'] == "?", 0.5, dados['El-salvador'])
dados['El-salvador'] = np.where(dados['El-salvador'] == "y", 1, dados['El-salvador'])

#Religious [n = no, y = yes]
dados['Religious'] = np.where(dados['Religious'] == "n", 0, dados['Religious'])
dados['Religious'] = np.where(dados['Religious'] == "?", 0.5, dados['Religious'])
dados['Religious'] = np.where(dados['Religious'] == "y", 1, dados['Religious'])

#Anti-satellite [n = no, y = yes]
dados['Anti-satellite'] = np.where(dados['Anti-satellite'] == "n", 0, dados['Anti-satellite'])
dados['Anti-satellite'] = np.where(dados['Anti-satellite'] == "?", 0.5, dados['Anti-satellite'])
dados['Anti-satellite'] = np.where(dados['Anti-satellite'] == "y", 1, dados['Anti-satellite'])

#Nicaraguan [n = no, y = yes]
dados['Nicaraguan'] = np.where(dados['Nicaraguan'] == "n", 0, dados['Nicaraguan'])
dados['Nicaraguan'] = np.where(dados['Nicaraguan'] == "?", 0.5, dados['Nicaraguan'])
dados['Nicaraguan'] = np.where(dados['Nicaraguan'] == "y", 1, dados['Nicaraguan'])

#Mx-missile [n = no, y = yes]
dados['Mx-missile'] = np.where(dados['Mx-missile'] == "n", 0, dados['Mx-missile'])
dados['Mx-missile'] = np.where(dados['Mx-missile'] == "?", 0.5, dados['Mx-missile'])
dados['Mx-missile'] = np.where(dados['Mx-missile'] == "y", 1, dados['Mx-missile'])

#Immigration [n = no, y = yes]
dados['Immigration'] = np.where(dados['Immigration'] == "n", 0, dados['Immigration'])
dados['Immigration'] = np.where(dados['Immigration'] == "?", 0.5, dados['Immigration'])
dados['Immigration'] = np.where(dados['Immigration'] == "y", 1, dados['Immigration'])

#Synfuels [n = no, y = yes]
dados['Synfuels'] = np.where(dados['Synfuels'] == "n", 0, dados['Synfuels'])
dados['Synfuels'] = np.where(dados['Synfuels'] == "?", 0.5, dados['Synfuels'])
dados['Synfuels'] = np.where(dados['Synfuels'] == "y", 1, dados['Synfuels'])

#Education-spending [n = no, y = yes]
dados['Education-spending'] = np.where(dados['Education-spending'] == "n", 0, dados['Education-spending'])
dados['Education-spending'] = np.where(dados['Education-spending'] == "?", 0.5, dados['Education-spending'])
dados['Education-spending'] = np.where(dados['Education-spending'] == "y", 1, dados['Education-spending'])

#Superfund [n = no, y = yes]
dados['Superfund'] = np.where(dados['Superfund'] == "n", 0, dados['Superfund'])
dados['Superfund'] = np.where(dados['Superfund'] == "?", 0.5, dados['Superfund'])
dados['Superfund'] = np.where(dados['Superfund'] == "y", 1, dados['Superfund'])

#Crime [n = no, y = yes]
dados['Crime'] = np.where(dados['Crime'] == "n", 0, dados['Crime'])
dados['Crime'] = np.where(dados['Crime'] == "?", 0.5, dados['Crime'])
dados['Crime'] = np.where(dados['Crime'] == "y", 1, dados['Crime'])

#Duty-fre-exports [n = no, y = yes]
dados['Duty-fre-exports'] = np.where(dados['Duty-fre-exports'] == "n", 0, dados['Duty-fre-exports'])
dados['Duty-fre-exports'] = np.where(dados['Duty-fre-exports'] == "?", 0.5, dados['Duty-fre-exports'])
dados['Duty-fre-exports'] = np.where(dados['Duty-fre-exports'] == "y", 1, dados['Duty-fre-exports'])

#Export-administration [n = no, y = yes]
dados['Export-administration'] = np.where(dados['Export-administration'] == "n", 0, dados['Export-administration'])
dados['Export-administration'] = np.where(dados['Export-administration'] == "?", 0.5, dados['Export-administration'])
dados['Export-administration'] = np.where(dados['Export-administration'] == "y", 1, dados['Export-administration'])


In [ ]:
for columns in ['Handicapped-infants','Water-project', 'Adoption', 'Physician', 'El-salvador', 'Religious', 'Anti-satellite', 'Nicaraguan','Mx-missile', 'Immigration', 'Synfuels', 'Education-spending','Superfund', 'Crime', 'Duty-fre-exports', 'Export-administration']:
  print (dados[columns].value_counts())

0.0    236
1.0    187
0.5     12
Name: Handicapped-infants, dtype: int64
1.0    195
0.0    192
0.5     48
Name: Water-project, dtype: int64
1.0    253
0.0    171
0.5     11
Name: Adoption, dtype: int64
0.0    247
1.0    177
0.5     11
Name: Physician, dtype: int64
1.0    212
0.0    208
0.5     15
Name: El-salvador, dtype: int64
1.0    272
0.0    152
0.5     11
Name: Religious, dtype: int64
1.0    239
0.0    182
0.5     14
Name: Anti-satellite, dtype: int64
1.0    242
0.0    178
0.5     15
Name: Nicaraguan, dtype: int64
1.0    207
0.0    206
0.5     22
Name: Mx-missile, dtype: int64
1.0    216
0.0    212
0.5      7
Name: Immigration, dtype: int64
0.0    264
1.0    150
0.5     21
Name: Synfuels, dtype: int64
0.0    233
1.0    171
0.5     31
Name: Education-spending, dtype: int64
1.0    209
0.0    201
0.5     25
Name: Superfund, dtype: int64
1.0    248
0.0    170
0.5     17
Name: Crime, dtype: int64
0.0    233
1.0    174
0.5     28
Name: Duty-fre-exports, dtype: int64
1.0    269
0.5    10

In [ ]:
dados.head()

Class Handicapped-infants Water-project Adoption Physician El-salvador  \
0     2                   0             1        0         1           1   
1     2                   0             1        0         1           1   
2     1                 0.5             1        1       0.5           1   
3     1                   0             1        1         0         0.5   
4     1                   1             1        1         0           1   

  Religious Anti-satellite Nicaraguan Mx-missile Immigration Synfuels  \
0         1              0          0          0           1      0.5   
1         1              0          0          0           0        0   
2         1              0          0          0           0        1   
3         1              0          0          0           0        1   
4         1              0          0          0           0        1   

  Education-spending Superfund Crime Duty-fre-exports Export-administration  
0                  1         1     1                0                     1  
1                  1         1     1                0                   0.5  
2                  0         1     1                0                     0  
3                  0         1     0                0                     1  
4                0.5         1     1                1                     1

## Seleção de Características (features)

In [ ]:
feature_cols = ['Handicapped-infants','Water-project', 'Adoption', 'Physician', 'El-salvador', 'Religious', 'Anti-satellite', 'Nicaraguan','Mx-missile', 'Immigration', 'Synfuels', 'Education-spending','Superfund', 'Crime', 'Duty-fre-exports', 'Export-administration']
X = dados[feature_cols]
Y = dados.Class

In [ ]:
Y
Y=Y.astype('int')

##Separação do Conjunto de Dados: Treinamento e Teste

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)
x_train1, x_train2, y_train1, y_train2 = train_test_split(x_train, y_train, test_size=0.5, shuffle=False)

In [ ]:
print('Tamanho do conjunto de treinamento: %i' %x_train.shape[0])
print('Tamanho do conjunto de treinamento1: %i' %x_train1.shape[0])
print('Tamanho do conjunto de treinamento2: %i' %x_train2.shape[0])
print('Tamanho do conjunto de teste: %i' %y_test.shape[0])

Tamanho do conjunto de treinamento: 348
Tamanho do conjunto de treinamento1: 174
Tamanho do conjunto de treinamento2: 174
Tamanho do conjunto de teste: 87


In [ ]:
dados[:10]

Class Handicapped-infants Water-project Adoption Physician El-salvador  \
0     2                   0             1        0         1           1   
1     2                   0             1        0         1           1   
2     1                 0.5             1        1       0.5           1   
3     1                   0             1        1         0         0.5   
4     1                   1             1        1         0           1   
5     1                   0             1        1         0           1   
6     1                   0             1        0         1           1   
7     2                   0             1        0         1           1   
8     2                   0             1        0         1           1   
9     1                   1             1        1         0           0   

  Religious Anti-satellite Nicaraguan Mx-missile Immigration Synfuels  \
0         1              0          0          0           1      0.5   
1         1              0          0          0           0        0   
2         1              0          0          0           0        1   
3         1              0          0          0           0        1   
4         1              0          0          0           0        1   
5         1              0          0          0           0        0   
6         1              0          0          0           0        0   
7         1              0          0          0           0        0   
8         1              0          0          0           0        0   
9         0              1          1          1           0        0   

  Education-spending Superfund Crime Duty-fre-exports Export-administration  
0                  1         1     1                0                     1  
1                  1         1     1                0                   0.5  
2                  0         1     1                0                     0  
3                  0         1     0                0                     1  
4                0.5         1     1                1                     1  
5                  0         1     1                1                     1  
6                  0       0.5     1                1                     1  
7                  0         1     1              0.5                     1  
8                  1         1     1                0                     1  
9                  0         0     0              0.5                   0.5

##Treinando os Modelos Explicáveis
1a) Árvore de Decisão para classificar o conjunto de testes (treinada com o conjunto de treinamento 1);

2a) Árvore de Decisão para classificar o conjunto de testes (treinada com o conjunto de treinamento 2);

In [ ]:
classificadorExplicavel1 = DecisionTreeClassifier(criterion="entropy", max_depth=3)
classificadorExplicavel2 = DecisionTreeClassifier(criterion="entropy", max_depth=3)

modeloExplicavelOriginal = classificadorExplicavel1.fit(x_train1,y_train1)


modeloExplicavel2 = classificadorExplicavel2.fit(x_train2,y_train2)


predicaoExplicavel = modeloExplicavelOriginal.predict(x_test)

predicaoExplicavel2 = modeloExplicavel2.predict(x_test)


## Construindo (ou Treinando) os Modelos (parte 2)

Iremos instanciar e treinar os modelos caixa-preta a serem utilizados no laço.

Cada modelo caixa-preta é treinado uma única vez.

**Caixa-preta** (treinado com o conjunto de treinamento 1) para classificar o conjunto de testes, mas também para classificar o conjunto de treinamento 2 (para produzir dados a serem usados pelo modelo explicável [para explicar o caixa-preta]);

**Criamos um arranjo de modelos** para ser utilizado em um laço nos testes que seguem.


In [ ]:
from sklearn.dummy import DummyClassifier # Este classificador será usado como um baseline

# Modelos que poderão ser usados como "caixa-preta"
from sklearn.ensemble import RandomForestClassifier # Floresta Aleatória
from sklearn.linear_model import LogisticRegression # Regressão Logística
from sklearn.neural_network import MLPClassifier # Rede Neural MLP
from sklearn.naive_bayes import GaussianNB # Classificador Baysiano que utiliza distribuição Gaussiana
from sklearn.neighbors import KNeighborsClassifier # KNN - K-Vizinhos mais próximos
from sklearn import svm # SVM: Máquina de Vetores de Suporte


### Estes classificadores serão tratados como 'caixa-preta'
classificadorCaixaPreta1 = DummyClassifier(strategy='most_frequent', random_state=42, constant = None)
classificadorCaixaPreta2 = DecisionTreeClassifier()
classificadorCaixaPreta3 = RandomForestClassifier()
classificadorCaixaPreta4 = svm.SVC()
classificadorCaixaPreta5 = svm.SVC(kernel='poly')
classificadorCaixaPreta6 = LogisticRegression(max_iter=5000)
classificadorCaixaPreta7 = MLPClassifier(max_iter=5000)
classificadorCaixaPreta8 = GaussianNB()
classificadorCaixaPreta9 = KNeighborsClassifier(n_neighbors = 10)

# Criando um arranjo com o nome dos modelos (para aparecer impresso nos resultados)
nomes = ["Dummy", "Árvore de Decisão", "Floresta Aleatoria", "SVM (linear)", "SVM (polinomial)", "Regressão Logística", "Multilayer perceptron", "Gaussian Naive Bayes", "KNN"]


# Criando modelos para os classifidores caixa-preta
# Usando o conjunto de treinamento 1 e a respectiva variável alvo
modeloCaixaPreta1 = classificadorCaixaPreta1.fit(x_train1,y_train1)
modeloCaixaPreta2 = classificadorCaixaPreta2.fit(x_train1,y_train1)
modeloCaixaPreta3 = classificadorCaixaPreta3.fit(x_train1,y_train1)
modeloCaixaPreta4 = classificadorCaixaPreta4.fit(x_train1,y_train1)
modeloCaixaPreta5 = classificadorCaixaPreta5.fit(x_train1,y_train1)
modeloCaixaPreta6 = classificadorCaixaPreta6.fit(x_train1,y_train1)
modeloCaixaPreta7 = classificadorCaixaPreta7.fit(x_train1,y_train1)
modeloCaixaPreta8 = classificadorCaixaPreta8.fit(x_train1,y_train1)
modeloCaixaPreta9 = classificadorCaixaPreta9.fit(x_train1,y_train1)


# Criando um arranjo dos modelos caixa-preta criados
modelosCaixaPreta = [modeloCaixaPreta1, modeloCaixaPreta2, modeloCaixaPreta3, modeloCaixaPreta4, modeloCaixaPreta5, modeloCaixaPreta6, modeloCaixaPreta7, modeloCaixaPreta8, modeloCaixaPreta9]

## Avaliação dos Modelos
Os modelos são avaliados em relação à acurácia, precisão, revocação e medida F1.

Os itens **a** e **b** são relacionados unicamente com o modelo explicável e por isso são executados à parte.

**O foco principal é analisar:**

**[a] Desempenho do modelo 'explicável' 1 (treinado usando o conjunto de treinamento 1);**


[b] Desempenho do modelo 'explicável' 2 (treinado usando o conjunto de treinamento 2);

**[1] Desempenho do modelo 'caixa-preta';**

[2] Desempenho do modelo 'explicável' 1 "explicando" o modelo 'caixa-preta';

[3] Desempenho do modelo 'explicável' 2 (treinamento com variável alvo original) "explicando" o modelo 'caixa-preta';

**[4] Desempenho do modelo 'explicável' 3 (treinamento com saída do caixa-preta) "explicando" o modelo 'caixa-preta;**

**[5] Desempenho do modelo 'explicável' 3 (treinamento com saída do caixa-preta), mas aplicado à variável alvo do conjunto de testes.**


In [ ]:
print('[a] Resultados para Modelo Explicável (treinado com o conjunto de treinamento 1)')
print("Acurácia:",metrics.accuracy_score(y_test, predicaoExplicavel))
report=metrics.classification_report(y_test,predicaoExplicavel)
print(report)
print(confusion_matrix(y_test, predicaoExplicavel))

print('\n[b] Resultados para Modelo Explicável 2 (treinado com o conjunto de treinamento 2)')
print("Acurácia:",metrics.accuracy_score(y_test, predicaoExplicavel2))
report=metrics.classification_report(y_test,predicaoExplicavel2)
print(report)
print(confusion_matrix(y_test, predicaoExplicavel2))

[a] Resultados para Modelo Explicável (treinado com o conjunto de treinamento 1)
Acurácia: 0.9540229885057471
              precision    recall  f1-score   support

           1       0.98      0.95      0.96        56
           2       0.91      0.97      0.94        31

    accuracy                           0.95        87
   macro avg       0.95      0.96      0.95        87
weighted avg       0.96      0.95      0.95        87

[[53  3]
 [ 1 30]]

[b] Resultados para Modelo Explicável 2 (treinado com o conjunto de treinamento 2)
Acurácia: 0.9425287356321839
              precision    recall  f1-score   support

           1       0.96      0.95      0.95        56
           2       0.91      0.94      0.92        31

    accuracy                           0.94        87
   macro avg       0.93      0.94      0.94        87
weighted avg       0.94      0.94      0.94        87

[[53  3]
 [ 2 29]]


## Construindo (ou Treinando) os Modelos (parte 3)

Dentro do laço um novo modelo é treinado:

**Árvore de Decisão** para explicar o modelo caixa-preta(treinada com o conjunto de treinamento 2, mas usando como alvo a classificação produzida pelo modelo caixa-preta).

Este modelo também será testado para explicar a saída da Floresta Aleatória, mas também para classificar a variável alvo do conjunto de testes.

## Avaliação dos Modelos
Os modelos são avaliados em relação à acurácia, precisão, revocação e medida F1.

** Neste bloco serão executados os testes que envolvem os modelos caixa-preta. ** Estão destacados os principais resultados para a pesquisa, porém os cinco resultados serão produzidos.


**[1] Desempenho do modelo 'caixa-preta';**

[2] Desempenho do modelo 'explicável' 1 "explicando" o modelo 'caixa-preta';

[3] Desempenho do modelo 'explicável' 2 (treinamento com variável alvo original) "explicando" o modelo 'caixa-preta';

**[4] Desempenho do modelo 'explicável' 3 (treinamento com saída do caixa-preta) "explicando" o modelo 'caixa-preta;**

**[5] Desempenho do modelo 'explicável' 3 (treinamento com saída do caixa-preta), mas aplicado à variável alvo do conjunto de testes.**

In [ ]:
cont = 0
for m in modelosCaixaPreta:

  print("\n############################ " + nomes[cont] + " ############################\n")
  cont = cont + 1
  classificadorExplicavel3 = DecisionTreeClassifier(criterion="entropy", max_depth=3)

  # Realizando a predição inicial (caixa-preta para o teste)
  predicaoCaixaPreta = m.predict(x_test)
  # Produzindo as predições da variável alvo que serão usadas para explicar o caixa-preta
  predicaoCaixaPreta2a = m.predict(x_train2)

  # Treinando o modelo explicativo, com base na predição do modelo caixa-preta
  modeloExplicandoCaixaPreta = classificadorExplicavel3.fit(x_train2,predicaoCaixaPreta2a)

  # Realizando as predições com base no que foi aprendido com o modelo caixa-preta
  predicaoExplicandoCaixaPreta = modeloExplicandoCaixaPreta.predict(x_test)

  print('\n[1] Resultados para o Modelo Caixa-Preta')
  print("Acurácia:",metrics.accuracy_score(y_test, predicaoCaixaPreta))
  report=metrics.classification_report(y_test,predicaoCaixaPreta)
  print(report)
  print(confusion_matrix(y_test, predicaoCaixaPreta))


  print('\n[2] Resultados para o Modelo Explicável 1 - comparando saída com a do caixa preta e não com o target original ("explicando" o caixa-preta)')
  print("Acurácia:",metrics.accuracy_score(predicaoCaixaPreta, predicaoExplicavel))
  report=metrics.classification_report(predicaoCaixaPreta,predicaoExplicavel)
  print(report)
  print(confusion_matrix(predicaoCaixaPreta, predicaoExplicavel))

  print('\n[3] Resultados para o Modelo Explicável 2 (treinado com os dados de treinamento 2, mas comparando saída com a do caixa preta e não com o target original ["explicando" o caixa-preta])')
  print("Acurácia:",metrics.accuracy_score(predicaoCaixaPreta, predicaoExplicavel2))
  report=metrics.classification_report(predicaoCaixaPreta,predicaoExplicavel2)
  print(report)
  print(confusion_matrix(predicaoCaixaPreta, predicaoExplicavel2))

  print('\n[4] Resultados para o Modelo Explicável explicando o Caixa-Preta (este é o único modelo treinado com esta finalidade)')
  print("Acurácia:",metrics.accuracy_score(predicaoCaixaPreta, predicaoExplicandoCaixaPreta))
  report=metrics.classification_report(predicaoCaixaPreta,predicaoExplicandoCaixaPreta)
  print(report)
  print(confusion_matrix(predicaoCaixaPreta, predicaoExplicandoCaixaPreta))

  print('\n[5] Resultados do Modelo Explicável treinado com a saída do Caixa-Preta e aplicado aos dados de teste')
  print("Acurácia:",metrics.accuracy_score(y_test, predicaoExplicandoCaixaPreta))
  report=metrics.classification_report(y_test,predicaoExplicandoCaixaPreta)
  print(report)
  print(confusion_matrix(y_test, predicaoExplicandoCaixaPreta))

  print("\n\n\n")


############################ Dummy ############################


[1] Resultados para o Modelo Caixa-Preta
Acurácia: 0.6436781609195402
              precision    recall  f1-score   support

           1       0.64      1.00      0.78        56
           2       0.00      0.00      0.00        31

    accuracy                           0.64        87
   macro avg       0.32      0.50      0.39        87
weighted avg       0.41      0.64      0.50        87

[[56  0]
 [31  0]]

[2] Resultados para o Modelo Explicável 1 - comparando saída com a do caixa preta e não com o target original ("explicando" o caixa-preta)
Acurácia: 0.6206896551724138
              precision    recall  f1-score   support

           1       1.00      0.62      0.77        87
           2       0.00      0.00      0.00         0

    accuracy                           0.62        87
   macro avg       0.50      0.31      0.38        87
weighted avg       1.00      0.62      0.77        87

[[54 33]
 [ 0  0]]

[

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           1       0.98      0.95      0.96        56
           2       0.91      0.97      0.94        31

    accuracy                           0.95        87
   macro avg       0.95      0.96      0.95        87
weighted avg       0.96      0.95      0.95        87

[[53  3]
 [ 1 30]]





############################ SVM (linear) ############################


[1] Resultados para o Modelo Caixa-Preta
Acurácia: 0.9540229885057471
              precision    recall  f1-score   support

           1       0.98      0.95      0.96        56
           2       0.91      0.97      0.94        31

    accuracy                           0.95        87
   macro avg       0.95      0.96      0.95        87
weighted avg       0.96      0.95      0.95        87

[[53  3]
 [ 1 30]]

[2] Resultados para o Modelo Explicável 1 - comparando saída com a do caixa preta e não com o target original ("explicando" o caixa-preta)
Acurácia: 1.0
      